### ISSUE TITLE
Agregar coloreado a la pieza en ejecución actual

### ISSUE THREAD

**Issue by hugoruscitti** [Program-AR/pilas-bloques-jr#10]

**Comment by miguelgarcia** [comment]
@hugoruscitti Se te ocurre alguna forma de obtener desde app/routes/editor/scene.js una referencia al currentWorkspace que está en app/controller/editor/scene.js ?

Es necesario porque el código corre en los interpretes creados dentro del route, pero tiene que pintar elementos que están en el workspace activo.

**Comment by hugoruscitti** [comment]
@miguelgarcia se me ocurre que podríamos comunicarlos con señales, usando algo así: http://emberjs.com/api/classes/Ember.Evented.html 

También podríamos mover esa funcionalidad al controller no?

**Comment by miguelgarcia** [comment]
Investigándolo más creo que tendríamos que hacer 2 cosas, en primer lugar creo que el bloque a colorear tendría que ser una propiedad de ember-blockly, desde el controller solo habría que setearla y el componente encargarse de pintarlo. Que te parece ?

**Comment by hugoruscitti** [comment]
si @miguelgarcia, me parece buena idea. 

Por cierto, yo estoy con el #4 desde master, ¿te harías un branch para implementar este issue?.
