### ISSUE TITLE
Deshabilitar acciones mientras se ejecuta y simplificar el acceso al estado inicial (con edición)

### ISSUE THREAD

**Issue by hugoruscitti** [Program-AR/pilas-bloques-jr#12]
Cuando el programa está en ejecución el usuario no debería poder cambiar bloques, crear actores o guardar. Cualquier opción o herramienta de edición se debería ocultar o deshabilitar mientras dure la ejecución.

Pasa algo similar cuando se termina de ejecutar, en ese estado final el usuario solo debería poder volver al estado inicial, como indican los mensajes de ayuda:

![pilasbloquesjr 2016-10-13 23-55-37](https://cloud.githubusercontent.com/assets/99183/19374242/8bbb164c-91a0-11e6-8122-88c2a739d8d6.png)

Cargué un solo issue para las dos cosas porque creo que podemos encontrar una solución que resuelva los dos problemas juntos. Tal vez podríamos usar una estrategia como la que se utiliza generalmente al implementar dialogos modales (cubrir con un layer translucido la pantalla completa) o algo por el estilo.

**Comment by asanzo** [comment]
@hugoruscitti esto no va también en el sprint 13 (y como todos los de ese sprint puede cerrarse al mergear?)

**Comment by hugoruscitti** [comment]
si @asanzo, ahora le aplico el label y lo cierro.
