### ISSUE TITLE
Envío de mensajes sincrónico

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-jr#17]
Buenas!

Supongamos este caso:

Cangrejo:

```
Al ejecutar
   Envío mensaje
   Digo chau
```

Gato:

```
Al recibir mensaje
   Digo hola
```

El resultado es que dicen hola y chau **a la vez**, en vez de suceder primero el hola y luego el chau. En ScratchJr suceden **uno después del otro**. 

En cuanto tengamos el demo con los colores, mi idea es _avisarles a los de Tandil que lo prueben y preguntarles si tenemos que cambiarlo_.

Hasta entonces dejo este issue abierto, para que quede registro del problema. Y de paso pregunto: ¿Qué tan difícil sería implementar la sincronía? 

En EjerciciosPilas yo había resuelto este problema usando un comportamiento Secuencia en el que agregaba los comportamientos, tuneando el receptor de los mismos para que, si bien la secuencia fuera comportamiento del cangrejo (y apilada en la lista de comportamientos del cangrejo), en realidad el receptor fuera el gato.

**Comment by miguelgarcia** [comment]
Buneas !!

Como está hecho ahora un actor después de enviar un mensaje sigue con su trabajo, no espera a que el mensaje haya sido atendido por uno o más actores.
   El código de todos los actores se ejecuta en forma concurrente, el secuenciamento de acciones se respeta dentro de cada actor, pero si por ejemplo dos actores tienen como primera acción decir "hola", los dos lo van a hacer casi simultáneamente, sin esperar a que el otro termine de hablar..
  Si la idea con los mensajes es esperar a que sean procesados entonces tenemos que definir varias cosas:

- Si un mensaje es atendido por varios actores a cuantos esperamos ? uno o todos
- Si un mensaje no es atendido por ningún actor, entonces el emisor se bloquea para siempre o sigue como si nada ?
- Deadlocks A emite "Rojo", B recibe "rojo" y emite "verde" que es atendido por A, pero A no puede atenderlo porque está esperando que B termine de atender "rojo"

  Si definimos estos puntos podemos modificar la forma en que funciona ahora

Saludos !

**Comment by asanzo** [comment]
Ok chequeo con tandil y reviso Scratch Jr para ver qué hacemos.

**Comment by asanzo** [comment]
Por ahora Tandil puede vivir sin esto.
