### ISSUE TITLE
Comando Decir provoca error

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-jr#20]
El error que provoca es "Unexpected token (42:21)"

![seleccion_009](https://cloud.githubusercontent.com/assets/5421992/20812361/feae7ef8-b7ef-11e6-936f-de2de64fc513.png)

Y esto es porque el código que escupe es:

```javascript
hacer("DecirMensaje", {
        mensaje: Hola!!!
    });
```

Cuando debería ser con comillas:

```javascript
hacer("DecirMensaje", {
        mensaje: "Hola!!!"
    });
```

Incidentalmente, también permite Javascript injection, pero no es un problema grave, creo.

**Comment by hugoruscitti** [comment]
Teníamos un problema en el deploy automático desde travis, se estaba mostrando la versión anterior... ahora está la 0.1.8 y funciona correctamente:

http://pilas-bloques-jr.surge.sh/

**Comment by asanzo** [comment]
Me sigue pasando lo mismo, tanto en

http://pilas-bloques-jr.surge.sh/

Como en

http://develop-pilas-bloques-jr.surge.sh/

**Comment by hugoruscitti** [comment]
¿tendremos algún tema con el cache?, ¿que te muestra en el cuadro de versión?

A mi me muestra 0.1.8:

![pilas bloques jr 2016-12-02 15-27-43](https://cloud.githubusercontent.com/assets/99183/20845459/f6c3e822-b8a3-11e6-9b63-37a49fb66499.png)

**Comment by asanzo** [comment]
Muestra eso. Lo probé en 3 navegadores diferentes en 3 compus diferentes.

**Comment by hugoruscitti** [comment]
Si, tenés razón. Ahí pude reproducirlo, mil disculpas, en breve subo el arreglo.

(y agrego un issue para ponerle tests a esto cuanto antes)

**Comment by hugoruscitti** [comment]
Ahí pude corregirlo, armé el release 0.1.9 y con ello se actualizó el sitio en surge (http://pilas-bloques-jr.surge.sh/) y los binarios para usar offline (https://github.com/Program-AR/pilas-bloques-jr/releases)
