### ISSUE TITLE
Actor por defecto seleccionado

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-jr#22]
Apenas abre un escenario, aparece un actor por defecto. Esto me parece correcto.

![seleccion_011](https://cloud.githubusercontent.com/assets/5421992/20845516/4a7ff87a-b8a4-11e6-9aa0-8cd0adab9f3e.png)

El problema es que, como no está seleccionado, no aparece el toolbox completo. Toma un rato encontrar dónde hay que hacer click para que aparezcan (Click en la pestaña "Cangrejo"). Aún conociendo la app me parece molesto.

Estaría bueno que apareciera seleccionado

**Comment by asanzo** [comment]
@hugoruscitti Esto no está hecho en el sprint13 ya?

**Comment by hugoruscitti** [comment]
Si @asanzo ahí lo coloqué en la pila del sprint 13.

Ahora estoy haciendo el merge, así que en cuanto termino reviso la lista de issues completa y voy cerrando verificando que efectivamente queden en el merge.
