### ISSUE TITLE
Llevar el commit de cambio de imágenes y nombres a develop (y revertirlo en master)

### ISSUE THREAD

**Issue by hugoruscitti** [Program-AR/pilas-bloques-jr#27]

**Comment by asanzo** [comment]
Hola @hugoruscitti !!!

Dos cosas:

1. Esto va en pilas-bloques XD
1. Mientras tanto creé un branch https://github.com/Program-AR/pilas-bloques/tree/cambiosParaRelease1.1 que pienso mergear cuando hagas este revert :D

**Comment by hugoruscitti** [comment]
Listo @asanzo, el cambio de @digitalh se movió al branch develop:

https://github.com/Program-AR/pilas-bloques/commit/ac7092f4a4be098368386d6dfcdc39c0df33769c

y en master se hizo un revert para volver al mismo estado del repositorio en el commit anterior:

https://github.com/Program-AR/pilas-bloques/commit/91407945dae15a65c3f05410f63ad5691ecdcc54
