### ISSUE TITLE
Bloques "Aparecer" y "Desaparecer"

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-jr#29]
Deben funcionar similarmente a los bloques de Scratch Jr:

![seleccion_023](https://cloud.githubusercontent.com/assets/5421992/21572790/1a92b61a-cebc-11e6-8a1e-b3cf6f72df5d.png)

**Comment by hugoruscitti** [comment]
Se resolvió en el sprint 14.
