### ISSUE TITLE
La ejecución parece no terminar

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-jr#32]
Relacionado con #9 y #12 

Una crítica que nos hicieron desde UNCPBA es que _pareciera como que nunca deja de ejecutar_:

![seleccion_050](https://cloud.githubusercontent.com/assets/5421992/22382043/c679ef24-e4a2-11e6-9ce2-88f883848afb.png)

Estaría bueno que hubiera _algún cambio al finalizar la ejecución_. ¿Quizá invertirse ese grisado? Y volver a tener el botón reiniciar:

![seleccion_051](https://cloud.githubusercontent.com/assets/5421992/22382207/74da246c-e4a3-11e6-9ffa-033f389ff8bd.png)

Click en el grisado de la escena ó en reiniciar debería producir el reinicio.

¿Qué les parece?

**Comment by hugoruscitti** [comment]
![sin titulo 4 2017-03-29 16-36-24](https://cloud.githubusercontent.com/assets/99183/24530941/a942a904-158b-11e7-968a-712a06fbfc47.png)

**Comment by asanzo** [comment]
Buenas! Estalla travis:

https://travis-ci.org/Program-AR/pilas-bloques-jr/jobs/216985952

**Comment by hugoruscitti** [comment]
El error al correr los tests en travis se producía porque ember-cli ya no es compatible con versiones 4.x de nodejs.

Modifiqué el archivo travis.yml en el commit https://github.com/Program-AR/pilas-bloques-jr/commit/d42b85d61eeeedf65c548b7f39906cecd04f32c2

y los tests vuelven a correr bien:

https://travis-ci.org/Program-AR/pilas-bloques-jr/builds/217804634
